### ISSUE TITLE
Slow query for full data view without gene in selected

### ISSUE THREAD

**Issue by mkroon1** [LOVDnl/LOVD3#102] opened 2016-07-20 14:45 UTC
Slow execution query for custom viewlist that belongs to the full view of variants, but where no gene is specified in the where clause (the latter should not happen!)

**Comment by mkroon1** [comment] 2017-08-24 15:39
Currently there are no entries in the slow query log that show instances of the full data view without a selected gene.

Will check on this later.

**Comment by mkroon1** [comment] 2017-09-20 14:01
Moved issue to next milestone in order to check again if this issue presents itself in the logs.

**Comment by ifokkema** [comment] 2017-10-11 10:29
I'm pretty sure this is a duplicate of #292, and it's been fixed in the last release.

**Closed** 2017-10-11 11:03 UTC
Labels: bug minor
