### ISSUE TITLE
Find & replace error on searching for "*"

### ISSUE THREAD

**Issue by mkroon1** [LOVDnl/LOVD3#187] opened 2017-02-17 12:46 UTC
Searching for "*" in the find & replace tool for viewlists results in an error. (reported by J)

![error](https://cloud.githubusercontent.com/assets/17007949/23065732/64933876-f517-11e6-9325-76fc4e6271f2.png)

**Comment by mkroon1** [comment] 2017-11-14 12:48
I cannot reproduce this locally with data from shared install. (I don't want to try something like this on production) Filtering on columns before or during the preview process works without problems. So at least this issue seems to be dependent on specific instances of the data.

I'll leave the issue open for now, as a reminder to check this again before release.

**Comment by ifokkema** [comment] 2018-03-14 02:04
Closing, can't reproduce.

**Closed by ifokkema** 2018-03-14 02:04 UTC
Labels: bug trivial
