### ISSUE TITLE
Custom link is not active on the variant annotation page while active in variants table

### ISSUE THREAD

**Issue by tsimakova** [LOVDnl/LOVD3#165] opened 2016-12-23 15:23 UTC
I have created a custom link (CFTR2v2) and added this link to a new custom data column (CFTR2v2). For the variant ID0000001196 the link is active in the varaints table. However it is broken on the variant annotation page.  The database availbale at: http://seqdb.parseq.pro/genes. I guess the problem is associated with URL encoding.

**Comment by ifokkema** [comment] 2016-12-23 19:04
Hi there!
I've taken a look at the database. Do you mean the link that is pointing at cftr2.org? In the `VariantOnGenome/CFTR2` column? That link doesn't work for me from any view from your database, but it seems to be a problem at the cftr2.org website. If you mean a different custom link, or you find a page that does have a link that work, can you share with me the direct URL to that page?
Thanks!

**Comment by tsimakova** [comment] 2016-12-26 10:24
Hello!
I have the problem with the column VariantOnTranscript/CFTR2v2 for the variant 621+1G>T (ID0000001196).  Please look at screenshots with the correct and broken links: https://drive.google.com/open?id=0B5GGg1fLQsySeTZmZmcyUkx2VWs

**Comment by ifokkema** [comment] 2016-12-29 13:46
Ah, than you, I see now. Can you please send us the custom link settings, so we can try to reproduce the problem? Then we can create a fix.

**Comment by tsimakova** [comment] 2017-01-09 06:44
Hello,

here is the link settings https://drive.google.com/drive/folders/0B5GGg1fLQsySeTZmZmcyUkx2VWs?usp=sharing

**Comment by mkroon1** [comment] 2017-02-13 17:16
Hi all,

I've tried to reproduce the issue. I can't get it to work properly on any view. The problem does indeed seem to be related to URL encoding. We currently don't perform URL encoding on custom links, as the replacement text allows HTML -- which shouldn't be URL-encoded.

However, even if LOVD would encode the URL, I suspect it won't work with the cftr2.org website, as they seem to decode the url input twice! Looking at a variant which is available in the CFTR2 database: `621+1G->T`, the following un-encoded url doesn't work:

* https://cftr2.org/mutation/general/621+1G->T

Encoding the variant once, still doesn't work:

* https://cftr2.org/mutation/general/621%2B1G-%3ET

Encoding the variant a second time, does work:

* https://cftr2.org/mutation/general/621%252B1G-%253ET

@tsimakova: Looking at your database, I see you're now linking to the CFTR2 database with the mutation_id. Is that a suitable workaround for you?

**Comment by ifokkema** [comment] 2017-06-19 20:10
Hi @tsimakova ,

I have taken another look, copied your custom link settings, and added a few entries, but our test LOVD instance doesn't show the same problems as your LOVD instance. Like mentioned before, the issue with the links not working could be solved by using the encoded mutation ID from the CFTR2 website. So, from the example, linking to https://cftr2.org/mutation/general/621%252B1G-%253ET will show the page properly.

But your examples of a link no longer working on the variant detail page is strange. If you'd still like us to investigate more why your LOVD behaves differently, please upgrade your LOVD instance to the latest LOVD version, and try again. If it still shows the problem, let us know.

**Comment by ifokkema** [comment] 2017-09-11 10:45
Hi @tsimakova, have you had time to review this? Above I have proposed a change that should fix the problem you're seeing, but fully investigating this will require an upgrade of your LOVD instance, as described above. Otherwise, we'll just close this issue.

**Comment by ifokkema** [comment] 2017-10-06 13:41
Closing as invalid, as no further input has been given.

**Closed by ifokkema** 2017-10-06 13:41 UTC
