### ISSUE TITLE
Find & Replace improvements

### ISSUE THREAD

**Issue by ifokkema** [LOVDnl/LOVD3#127] opened 2016-09-09 15:00 UTC
After the first release of Find & Replace, some improvements are needed:
- [x] Run `checkFields()` on the data, to ensure correctness of the resulting string.
  - [x] Really make sure this step can not be evaded.
  - [ ] Then, more columns can be allowed to be "editable" by F&R.
- [x] Numeric columns can now receive text characters, which results in empty fields.
  - [x] Do allow some notation, though. Not sure if MySQL's way of checking what numeric corresponds to PHP's `is_numeric()`.
- [x] When you select a column, then resubmit the VL, suddenly a tooltip for F&R options menu is shown. Perhaps this is meant to show directly after selecting a column?
- [x] Document Find and Replace.
- [x] Look at inc-lib-columns.php, see where functions are used, and decide on what to do with that file.

**Comment by mkroon1** [comment] 2017-11-10 14:44
Non-numeric values for numeric columns should be caught by `checkFields()`. I don't think an extra check in MySQL is needed there.

> When you select a column, then resubmit the VL, suddenly a tooltip for F&R options menu is shown. Perhaps this is meant to show directly after selecting a column?

Currently unable to reproduce this issue on both Chrome and Firefox. Perhaps the issue was resolved inadvertently.

**Comment by ifokkema** [comment] 2018-01-26 13:58
Thanks, both problems seems to have been solved indeed!

I found some other issues, but have corrected them. I will go through it again just to be sure, but probably it's OK like this :smile:

**Closed** 2018-01-26 18:37 UTC
